### ISSUE TITLE
Please consider using customary country names provided by the Unicode CLDR.

### ISSUE THREAD

**Issue by hanteng** [datasets/country-codes#16]
Please consider using *customary* country names instead of the current official names. Customary country names provided by the Unicode CLDR are used widely by major websites including Google.

As a bonus, the Unicode CLDR provides additional country names in many languages, and thus better for wider application of the country-codes.

I have provided a full country name list from the latest Unicode CLDR 25 in the forked version below:
https://github.com/hanteng/country-codes/tree/master/data/country-names

Please consider replacing or adding the names into the country-codes dataset. 

More here: 
http://people.oii.ox.ac.uk/hanteng/zh/2014/05/28/whats-in-a-name-country-names-are-technical-cultural-and-political/

**Comment by rgrp** [comment]
@hanteng this seems a great suggestion - @ewheeler any thoughts as maintainer?

@hanteng if we did do this would you be up for turning your fork into a pull request?

**Comment by hanteng** [comment]
@rgrp Sure. Please let me know how and what to add a field of CLDR customary name. I just recently do some work based on Babel python module

**Comment by rgrp** [comment]
@hanteng  can you submit a PR so we can review ...

**Comment by ewheeler** [comment]
@hanteng @rgrp yes this would be fantastic to include. PR would be most welcome!

**Comment by JoshMcCullough** [comment]
Would this fix the `"Venezuela, Bolivarian Republic of"` issue? (E.g. let's just call this country "Venezuela" -- as everyone knows it.)

**Comment by rgrp** [comment]
@JoshMcCullough yes i imagine it would.

@gsilvapt - could you take a look at @hanteng work in https://github.com/hanteng/country-codes/tree/master/data/country-names and see what it would take to integrate here - or whether it should even be a separate data package.

**Comment by gsilvapt** [comment]
@rgrp  I think we can create a package from this and even add another script to the guides to help users easily replace country codes. However, getting used to it may be troublesome.

I am not sure what this fixes though? @hanteng can you enlighten me please?

**Comment by hanteng** [comment]
@gsilvapt Please refer to the Unicode CLDR document here: http://cldr.unicode.org/translation/country-names

Customary Names
> The ISO names and the "official" names are often not the best ones. The goal is the most customary name used in your language, even if it is not the official name. For example, for the territory name in English you would use "Switzerland" instead of "Swiss Confederation", and use "United Kingdom" instead of "The United Kingdom of Great Britain and Northern Ireland". One of the best sources for customary usage is to look at what common major publications such as newspapers and magazines do, the equivalents of The Economist, NY Times, BBC, WSJ, etc. in your language. You can look at style guides if available or at a sampling of pages, but favor publications’ rather than academic style guidelines. For example, to see how "Congo" is used in French, one might search for Congo on Le Monde and on other publications.

Practical benefits include not only the "Venezuela" case @JoshMcCullough mentions but also includes examples such as:
* Korea, Democratic People's Republic of  
* Korea, Republic of

The above official names provided by the ISO may not be useful as the customary names such as North Korea and South Korea as listed in Unicode CLDR. 

This is very important difference especially if the data is meant to be visualized or designed into interactive infographics where shorter customary names are better than longer official names.

**Comment by JoshMcCullough** [comment]
I appreciate this dataset but, honestly, until the country names are as @hanteng suggested, I can't use it. I need the country names I'm using to be what people would expect, otherwise, most users would be confused. Perhaps we just need a new column for the "customary name"?

**Comment by rgrp** [comment]
@JoshMcCullough we are 👍  on getting this in and adding the relevant column.

@hanteng can you submit a PR with just the english customary names for now?

**Comment by gsilvapt** [comment]
I think we could advise the usage of the English customary names in our core datasets and forward people to an official dataset if they need the country names in their local language. How does that sound, @hanteng @rgrp ?

**Comment by hanteng** [comment]
@rgrp @gsilvapt I agree on using the English customary names (as defined/updated by Unicode CLDR). It is also a good advice by gsilvapt to point users to an official dataset (for official names e.g. http://unstats.un.org/unsd/methods/m49/m49alpha.htm) or an industry-focus dataset (for customary names for localization purposes such as Unicode CLDR). This can be mentioned simply in the Readme or similar file.

@JoshMcCullough I hope that the English customary names, as defined/updated by Unicode CLDR, match what you and your users will expect.

If you all agree, I can help submitting a pull request (PR) with just the English customary names.

**Comment by JoshMcCullough** [comment]
@hanteng Yes, this sounds good.

**Comment by rgrp** [comment]
@hanteng sounds good and please submit a PR :-)

Note, in terms of way of doing this i would recommend the following:

- Store list of customary names (plus a country identifier that would allow merging into the main file) in a separate CSV
- Join this into the main country code file using a script

This was the process is easily repeatable in future and follows the current build process.
