### ISSUE TITLE
get_countries_of_earth.py fails since ISO removed iso3166 list

### ISSUE THREAD

**Issue by ojab** [datasets/country-codes#20]
I want to add TLDs and ITU designation in English (from [here](http://www.itu.int/online/mm/scripts/mm.list?_languageid=1&_from=&_search=ITUstates&regionvarnam=ctry_councilregion&_territories=&_map=n&_sort=1&_f1=CHECKED&_f8=CHECKED&_f20=CHECKED
)), but since ISO no longer provides iso3166 lists for free -- ./scripts/get_countries_of_earth.py fails.
Can I expect that list-en1-semic-3.txt & list-fr1-semic.txt are already downloaded or script should be fixed (add files to repo/change it fetch info from other source like [maxmind](http://dev.maxmind.com/static/csv/codes/iso3166.csv))?
So how should I proceed with editing get_countries_of_earth.py?

**Comment by makmanalp** [comment]
https://www.drupal.org/node/1033764

**Comment by makmanalp** [comment]
Maybe some semblance of something official here: http://www.loc.gov/standards/iso639-2/php/English_list.php

**Comment by danfowler** [comment]
Another option:

http://unstats.un.org/unsd/methods/m49/m49alpha.htm
http://unstats.un.org/unsd/methods/m49/m49alphaf.htm

**Comment by makmanalp** [comment]
The UN stats one is a great idea actually @danfowler.

**Comment by hanteng** [comment]
Per https://github.com/datasets/country-codes/issues/16

May I suggest that both English and French names use the Unicode CLDR json data source hosted also in github?  

I can do French easily if needed. Currently only the English country names are updated with a pull request (PR) https://github.com/datasets/country-codes/pull/31

**Comment by ewheeler** [comment]
This seems to be a trend, unfortunately.
ISO 4217 currency codes are no longer freely available at http://www.currency-iso.org/en/home/tables/table-a1.html

**Comment by ewheeler** [comment]
I pushed a work-in-progress branch that refactors `get_countries_of_earth.py` into independent scripts with a `Makefile` to construct the dataset
https://github.com/datasets/country-codes/tree/refactor-script

This should make it a lot easier to swap upstream data sources and contribute additional codes. would love any feedback/suggestions!

**Comment by ewheeler** [comment]
Refactor branch has been merged so closing this issue.

Will be on the lookout for a replacement upstream source for ISO 4217 currency codes
