### ISSUE TITLE
add colums or another table of official names in each official lang 

### ISSUE THREAD

**Issue by ppKrauss** [datasets/country-codes#21]
There are other official langs than *en* and *fr*, but there are many.... As #15 suggest, the CSV can include "official langs", so, we can add more columns (or another new CSV) to show `name_es`, `name_pt`, etc. for the more used langs.

**Comment by ewheeler** [comment]
these are not each country's official languages, these are the country names published as part of ISO 3166

**Comment by ppKrauss** [comment]
Yes (!), like `name_fr` column...The official name of "Brazil" is "Brasil", and they say "Irã" not "Iran".
