### ISSUE TITLE
No date?

### ISSUE THREAD

**Issue by bcsteeve** [datasets/country-codes#27]
Perhaps I'm missing it, and perhaps it isn't viewed as important... but as someone just now finding this resource,  my very first question was "WHEN"?  I have no idea if this data is from yesterday or from 1990.  I just don't see a date anywhere.  So just a suggestion that a "last updated" could be useful on the download page, if not the file itself.

**Comment by ewheeler** [comment]
Good catch! Added a `last_modified` field to `datapackage.json`
https://github.com/datasets/country-codes/blob/master/datapackage.json#L6
