### ISSUE TITLE
Republic of Macedonia

### ISSUE THREAD

**Issue by ppKrauss** [datasets/country-codes#28]
See https://en.wikipedia.org/wiki/Republic_of_Macedonia

*"the former Yugoslav Republic of Macedonia"* was provisional, and today not used. Use "Republic of Macedonia" instead.

**Comment by ewheeler** [comment]
ISO 3166 official standard still uses "the former Yugoslav Republic of Macedonia"
https://www.iso.org/obp/ui/#iso:code:3166:MK
