### ISSUE TITLE
Adding continent codes for countries

### ISSUE THREAD

**Issue by zelima** [datasets/country-codes#30]
@ewheeler  It would be nice adding the [two digit continent code](http://data.okfn.org/data/core/continent-codes) to the country-codes. We could retrieve data about countries and their continents from [here](http://download.geonames.org/export/dump/countryInfo.txt )
@rgrp , @pdehaye would you mind leaving your thoughts here.

**Comment by rgrp** [comment]
@ewheeler any thoughts - would you be happy to get a pull request here?

**Comment by ewheeler** [comment]
@zelima @rgrp absolutely! great suggestion

**Comment by zelima** [comment]
@rgrp the best way would be to add the data manually, right? 
Working directly with CSV file - adding one last column with name Continent and filling with data one by one

**Comment by rgrp** [comment]
@zelima it would be worth scripting this - the overall built is scripted so hand done stuff may get lost:  https://github.com/datasets/country-codes/tree/master/scripts

Probably you want a separate csv which matches country ids to continents and we merge that into the final CSV as part of the build.

**Comment by ewheeler** [comment]
@zelima @rgrp 
i agree. i've been meaning to refactor the existing script and have the process executed by a makefile so that we can accommodate a cleaner build process that would let us substitute upstream sources more easily. 
generating a separate csv that can be merged would be ideal at this point

**Comment by zelima** [comment]
@rgrp @ewheeler Ok, got it. Will start as soon as I find time.

**Comment by hanteng** [comment]
Please consider using Unicode CLDR resources here instead:

http://www.unicode.org/repos/cldr/trunk/common/supplemental/subdivisions.xml

**Comment by hanteng** [comment]
I have done the scripts and data generation based on UN M.49 region categorization by two sources: United Nations Statistics Division and Unicode CLDR. 
https://github.com/hanteng/m49

The integrated table here: https://github.com/hanteng/m49/blob/master/data/_cf_m49_cldr__join.tsv

In the table, "left" refers to the data provided by United Nations Statistics Division whereas 'right' refers to the data provided by Unicode CLDR

**Comment by zelima** [comment]
@rgrp @ewheeler 
Datapackage for country-continents is ready.
You can view data [here](http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fzelima%2Fcountry-continents#resource-country-coninents)
[Repository itself](https://github.com/zelima/country-continents)
Could you suggest how to merge with country-codes?

**Comment by ewheeler** [comment]
Thanks, @zelima !

I've adapted your script here: https://github.com/datasets/country-codes/commit/2ab638af09b9ede34e56e3ff5dd553b7997aa3e2

Once I finish a bit of testing, we'll get these in.

**Comment by zelima** [comment]
@ewheeler Great!

**Comment by ElleshaHackett** [comment]
What about countries in multiple continents such as Russia? It is in Asia and Europe. Not only Europe. In fact, most of it's land is in Asia. I think it should be a one-on-multiple relation, right? Any official reference on this?

**Comment by clphillips** [comment]
The UN places Russian Federation squarely in Europe (https://unstats.un.org/unsd/methodology/m49/ select 'geographic regions') but wikipedia has them (unofficially) aggregated in both: https://en.m.wikipedia.org/wiki/List_of_sovereign_states_and_dependent_territories_by_continent_(data_file)

Unfortunately there appears to be no ISO standard.
