### ISSUE TITLE
Metadata button not working

### ISSUE THREAD

**Issue by patcon** [datasets/country-codes#32]
http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fdatasets%2Fcountry-codes#resource-country-codes

For the above dataset, metadata points to:
http://data.okfn.org/tools/country-codes/datapackage.json

> Cannot GET /tools/country-codes/datapackage.json

**Comment by ewheeler** [comment]
this is an issue in the datapackage viewer tool that runs on http://data.okfn.org

this metadata button issue is tracked elsewhere:

https://github.com/okfn/data.okfn.org-new/issues/9
https://github.com/frictionlessdata/project/issues/79
