### ISSUE TITLE
EDGAR Codes

### ISSUE THREAD

**Issue by marfi** [datasets/country-codes#33]
Apparantely the SEC has its own code system for countries.

https://www.sec.gov/edgar/searchedgar/edgarstatecodes.htm

I can add them if there's consensus that they are useful.

**Comment by ewheeler** [comment]
Interesting. 
Sure, would welcome a PR with these!

**Comment by marfi** [comment]
If PR stands for Pull Request - I did it a while ago :)

**Comment by ewheeler** [comment]
@marfi great! could you open against this repo? i dont see any pull requests open or closed for EDGAR codes here

**Comment by marfi** [comment]
Hm, strange let me see what happened.

**Comment by marfi** [comment]
Should be OK now, sorry.
