### ISSUE TITLE
ISO3166-1-Alpha-2 for Namibia is missing

### ISSUE THREAD

**Issue by kaiminglee** [datasets/country-codes#38]
Namibia's ISO 2char code is 'NA' but missing in the data. 

Probably, pandas read_csv was used somewhere in the processing, which interprets 'NA' as missing by default (use keep_default_na=False to prevent this).

**Comment by ewheeler** [comment]
Good catch, @kaiminglee ! thanks

We were also missing `Continent` for every country in North America (NA)...

Culprit turned out to be `csvkit`'s [csvsort](https://csvkit.readthedocs.io/en/0.9.1/scripts/csvsort.html) but calling with the `--no-inference` flag did the trick
