### ISSUE TITLE
GB (UK) & USD lost currencies

### ISSUE THREAD

**Issue by wodow** [datasets/country-codes#39]
Currency codes for GB & US, at least, were lost in the jumbo commit d4e48954df2c5fd6b23a4eca8749c1c2c05b185e.

Too long to check all the edits, so maybe revert?

**Comment by ewheeler** [comment]
Thanks for catching this, @wodow 

There was a bug in the currency code script that was swallowing errors, so several currencies were being excluded silently.
Have fixed GB, US, and a few more!

**Comment by wodow** [comment]
Thank you, @ewheeler 

I think unit tests or simple assertions on the output would help. (I could try taking a look at that later in the month.)

**Comment by ewheeler** [comment]
you're welcome, @wodow!

yes i agree that simple tests would help to avoid regressions. 

i've created a separate issue to track here: https://github.com/datasets/country-codes/issues/40
would welcome your thoughts and ideas!

cheers

**Comment by marcmarcet** [comment]
Can it be the reason taiwan is missing all its currency info?

https://github.com/datasets/country-codes/commit/d4e48954df2c5fd6b23a4eca8749c1c2c05b185e#diff-c1f0a2a818473ec463559fafe9ce27f5L218
