### ISSUE TITLE
Republic of Kosovo is missing in the list

### ISSUE THREAD

**Issue by rrusch** [datasets/country-codes#42]
https://en.wikipedia.org/wiki/Kosovo

**Comment by ewheeler** [comment]
Per the article you linked:

> XK is a "user assigned" ISO 3166 code not designated by the standard, but used by the European Commission, Switzerland, the Deutsche Bundesbank and other organisations.

Similarly, Kosovo unofficially has a dialing code for fixed line telephones (```+383```) but in [ITU's published standards](https://www.itu.int/itudoc/itu-t/ob-lists/icc/e164_763.pdf) this is labeled as a 'spare code' so is not included.

This dataset is a collection of official country code standards and currently Kosovo is not included in these published, upstream standards.
