### ISSUE TITLE
Czech Republic English name

### ISSUE THREAD

**Issue by rgieseke** [datasets/country-codes#45]
Hi,

the *Czech Republic* changed its English name to *Czechia*.

**Wikipedia**
https://en.wikipedia.org/wiki/Name_of_the_Czech_Republic

> Adoption of Czechia
[...]
> In 2013, Czech president Miloš Zeman recommended the wider official use of Czechia,[34] and on 14 April 2016, the country's political leadership agreed to make Czechia the official short name. The new name was approved by the Czech cabinet on 2 May 2016[35] as the Czech Republic's official short name and was published in the United Nations UNTERM and UNGEGN country name databases on July 5th, 2016. [36]

**Ministry of Foreign Affairs**
Short country name "Česko"/"Czechia" to be entered in UN databases
http://www.mzv.cz/jnp/en/issues_and_press/factsheets/x2016_04_21_the_completion_of_translations_of_the.html

It's not in the [UN Statistics](United Nations Statistics Division) list yet (last updated in 2013 it seems), but it is in use e.g. in the UN Treaty collection.

Not sure if it's worth updating/patching but wanted to note it here.

**Comment by ewheeler** [comment]
Thanks for flagging this, @rgieseke 

Doesn't look like this change has been made in the ISO-3166 standard yet: https://www.iso.org/obp/ui/#iso:code:3166:CZ

but will be sure to look out for this and update the dataset once the official ISO standard has changed.

**Comment by ewheeler** [comment]
Hey @rgieseke 
ISO made the change yesterday, so I've updated accordingly
Thanks again for bringing this to our attention!
