### ISSUE TITLE
CLDR v30.0.3 released

### ISSUE THREAD

**Issue by Mottie** [datasets/country-codes#48]
CLDR v30.0.3 was released on 2016-12-02 (http://cldr.unicode.org/index/downloads/cldr-30) and includes the following relevant changes:

* New script codes for Adlam, Bhaiksuki, Marchen, Newa, Osage
* Some support for new region codes EZ, UN (though names for EZ are not available in languages other than English).
* Updated english names for bn/Beng “Bangla”, mic “Mi'kmaq”, or “Odia”.
* Documented the use of script subtag “Zxxx” to indicate spoken or otherwise unwritten content.
* The set of language and script names for which translations are requested was revamped, leading to a substantial increase in the number of such names.
* Substantial new data has been added for likely subtags (e.g. to get the main script for each language).

----
Opps, should I have opened this issue in the https://github.com/datasets/language-codes repo?

**Comment by ewheeler** [comment]
we just fetch the customary country names from https://github.com/unicode-cldr/cldr-localenames-full/blob/master/main/en/territories.json

our source for languages is http://download.geonames.org/export/dump/countryInfo.txt

closing for now, but please report any issues in the language info in dataset. we can always use a different source if geonames is out of date or incomplete
