### ISSUE TITLE
Importer fails because datapackage descriptor doesn't match CSV

### ISSUE THREAD

**Issue by hozn** [datasets/country-codes#49]
Looks like fix for #47 broke ability for this dataset to be loaded (at least by the python datapackage), since CSV column name no longer matches what's in the `datapackage.json` file.

**Comment by hozn** [comment]
Hey ... any movement on this?  Your dataset is completely broken ...

**Comment by ewheeler** [comment]
Thanks for the report @hozn and sorry for the delayed fix!
