### ISSUE TITLE
add ITU's legal time

### ISSUE THREAD

**Issue by ewheeler** [datasets/country-codes#5]
available as .pdf and .doc here: http://www.itu.int/pub/T-SP-LT.1-2013
maybe use antiword to parse .doc

**Comment by ppKrauss** [comment]
Please explain or delete.. 

ITU = International Telecommunication Union.  But your link not works, "The Publication selected is not available".

**Comment by ewheeler** [comment]
ITU publishes a 'Legal time' standard which can now be found here: http://www.itu.int/pub/T-SP-LT.1-2014

Probably not worth including, as UTC offset can change throughout the year and that would be hard to represent in a sensible way. 
http://momentjs.com/ packages these data well

**Comment by ppKrauss** [comment]
thanks...  Yes, I agree (!).

PS: another related idea/suggestion is the [list of UTM zones of the country](https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system#UTM_zone).

**Comment by ewheeler** [comment]
closing as this will be packaged separately
