### ISSUE TITLE
Only one currency included for each country

### ISSUE THREAD

**Issue by wodow** [datasets/country-codes#50]
The entry for Namibia has ZAR incorrectly listed as the primary currency, presumably due to the country appearing twice in the official source data [1] (as ZAR is legal tender there): 

How should the import script handle this?

[1] http://www.currency-iso.org/dam/downloads/lists/list_one.xml

**Comment by wodow** [comment]
I am attempting to contact SNV re this but they are not making it straightforward (the contact from on currency-iso.org does not work).

**Comment by ewheeler** [comment]
Nice catch, @wodow 

Strange that both are included. As far as I can tell, the Namibian Dollar (NAD) is the only official currency even though it is pegged to the value of ZAR.

Looks like Panama, Lesotho, Haiti, El Salvador, Cuba, and Bhutan all have more than one appearance too.

My inclination is to update the import script and include multiple values per cell for these countries.

**Comment by wodow** [comment]
That makes sense, but it would also be useful to have a cell/column containing the official currency in the cases where there is unambiguously a single one.

Does the existing data source contain this? Is the concept even well-defined?

**Comment by ewheeler** [comment]
@wodow unfortunately the data source does not differentiate among multiple currencies listed for a single country. I don't think this is a well-defined concept, as I suspect that such countries have multiple currencies that are considered legal tender.

**Comment by wodow** [comment]
I understand and agree.

Given that, I think your suggestion to include lists of currencies (comma-separated?) in the relevant cell is the correct one. The client should be forced to choose.

**Comment by ewheeler** [comment]
@wodow including multiple currencies now. only funny part is minor units. i've included as comma separated. this could be ambiguous if multiple currencies each had different minor units, but luckily the existing multiple currencies have the same minor units...
