### ISSUE TITLE
Update link in repository description

### ISSUE THREAD

**Issue by ewheeler** [datasets/country-codes#58]
The link in the repository description (http://data.okfn.org/data/country-codes) now redirects to https://datahub.io/

Should update the link to either

http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fdatasets%2Fcountry-codes#resource-country-codes

or 

https://datahub.io/core/country-codes (however this one does not seem to update automatically to reflect repo changes)

**Comment by ewheeler** [comment]
@rufuspollock i'm not able to change repo description/settings, so would appreciate your help on this one

**Comment by rufuspollock** [comment]
@ewheeler will fix that both in redirect in data.okfn.org and in description on this repo 👍  - btw that was a very old link i think 😄

**Comment by ewheeler** [comment]
thanks @rufuspollock!!
