### ISSUE TITLE
Dial code broken for the Dominican Republic (DOM)

### ISSUE THREAD

**Issue by darnel** [datasets/country-codes#87]
Previously line 69 was

`DOM,"1-809,1-829,1-849",DOM,dr,Yes,214,72,DR,DR,DO,DOM,DOM,DOM,la República Dominicana,True,29,République dominicaine,...`

with three separate dial codes `1-809`, `1-829`, `1-849` which seems correct (https://en.wikipedia.org/wiki/Area_codes_809,_829,_and_849) but the following commit

https://github.com/datasets/country-codes/commit/a09b84ab199694aa3db18d7bfc15f632543db672#diff-99daf7ea0ec7335d0e8937a27e4fd2f024d8241703b6c084db4a48a698ad9c0b

changes line 68 to
`DOM,1-8091-8291-849,DOM,dr,Yes,214,72.0,DR,DR,DO,DOM,DOM,DOM,la República Dominicana,1,29.0,République dominicaine,...`

with single mixed dial code.  This extensive change (or not correctly detected by diff) may brings additional similar errors.

Thanks.

**Comment by gradedSystem** [comment]
@darnel  Noted will fix that tomorrow

**Comment by gradedSystem** [comment]
Should be fixed with this PR: https://github.com/datasets/country-codes/pull/89
